### ISSUE TITLE
libncursesw.so not found on void linux

### ISSUE THREAD

**Issue by dagit** [judah/terminfo#24]
I just tried to build vty, which in turn uses terminfo, on void linux but I got an error that `libncursesw.so` could not be found. I was able to workaround this by adding a symlink for `libncurses.so.6.0` to `libncursesw.so`.

Would it be possible to make terminfo a bit more permissive when looking for ncurses?

**Comment by judah** [comment]
Terminfo already looks for both `ncursesw` and `curses` (among others); I'm not sure why that didn't work for your machine:
 https://github.com/judah/terminfo/blob/master/configure.ac#L23

How did you build `vty`; was it with `stack` or `cabal`?

Can you please try (after temporarily undoing your symlink):

    cabal unpack terminfo-0.4.1.0
    cd terminfo-0.4.1.0
    cabal configure
    cabal repl

Then run `setupTermFromEnv` inside the REPL?  Let me know the output of those commands, which one fails, and also attach the contents of the `config.log` file that gets generated.

**Comment by dagit** [comment]
I'm sorry. I just realized I made a important and unfortunate typo in my original report. The difference in filenames should have just been the suffix `.6.0`. All filenames in question should be the `w` variant.

I removed my symlink and tried the command you suggested. The configure step fails:

```
$ cabal configure       
Resolving dependencies...
Configuring terminfo-0.4.1.0...
configure: WARNING: unrecognized options: --with-compiler
checking for gcc... /usr/bin/cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/bin/cc accepts -g... yes
checking for /usr/bin/cc option to accept ISO C89... none needed
checking for setupterm in -ltinfo... no
checking for setupterm in -lncursesw... no
checking for setupterm in -lncurses... no
checking for setupterm in -lcurses... no
configure: error: in `/home/dagit/tmp/terminfo-0.4.1.0':
configure: error: curses library not found, so this package cannot be built
See `config.log' for more details
```

The log doesn't contain anything interesting. I added the symlink back and the configure step succeeds.

At this point I don't know if I should be submitting a bug here or to the void linux maintainers, but it would be nice if the configure script was more permissive.

I hope that helps.

**Comment by dagit** [comment]
Okay. Turns out I'm an idiot. I thought I had installed the necessary `-devel` package but I'm pretty new to void-linux and it turns out I was mistaken. Once I installed that terminfo's configure finds the ncurses library.
