### ISSUE TITLE
Cut a release for GHC 8.4

### ISSUE THREAD

**Issue by bgamari** [judah/terminfo#27]
The GHC 8.4.1 release is quickly approaching and i would like to have all of the submodules finalized by next alpha. For this we'll need a new release.

**Comment by judah** [comment]
Done; I've released the latest master as `0.4.1.1` and pushed a tag of the same name.

**Comment by bgamari** [comment]
Judah Jacobson <notifications@github.com> writes:

> Done; I've released the latest master as `0.4.1.1` and pushed a tag of the same name.
>
Thanks for the quick turnaround!
