### ISSUE TITLE
The feild "category" is defined twice in terminfo.cabal

### ISSUE THREAD

**Issue by chitrak7** [judah/terminfo#28]
You have defined the field "category" twice in terminfo.cabal which is throwing warnings.
Should I push a PR removing this redundancy?
Name:           terminfo
Cabal-Version:  >=1.10
Version:        0.4.1.1
==>Category:       User Interfaces
License:        BSD3
License-File:   LICENSE
==>Copyright:      (c) Judah Jacobson
Author:         Judah Jacobson
Maintainer:     Judah Jacobson <judah.jacobson@gmail.com>
Category:       User Interfaces

@judah

**Comment by judah** [comment]
Sure, feel free to sent a PR.
