### ISSUE TITLE
Cut release for GHC 8.6.1

### ISSUE THREAD

**Issue by bgamari** [judah/terminfo#31]
Thanks in advance!

**Comment by bgamari** [comment]
Ping.

**Comment by judah** [comment]
Done in terminfo-0.4.1.2 (tag `0.4.1.2`).  Apologies for the delay.

**Comment by bgamari** [comment]
Judah Jacobson <notifications@github.com> writes:

> Done in terminfo-0.4.1.2 (tag `0.4.1.2`).  Apologies for the delay.
>
Thanks!
