### ISSUE TITLE
Active maintainer?

### ISSUE THREAD

**Issue by jtdaugherty** [judah/terminfo#48]
Greetings @bgamari and @judah!

I am curious about the status of this library and how much energy is available to maintain it (or will be in the future). I depend on this library as critical infrastructure for the `vty` and `brick` packages and I'm wondering if you'd like help maintaining this library (or would like someone to take over). I'm considering offering to do that, but I wanted to check with you and understand what your intentions are.

Thanks!

**Comment by judah** [comment]
Hi @jtdaugherty, as you've probably gathered I do not have much time for this library myself these days. I would be happy for you to help maintain it! I've gone ahead and added you as a collaborator alongside @bgamari (who I'll let weigh in with his thoughts, if any).
