### ISSUE TITLE
compile fails on ARM

### ISSUE THREAD

**Issue by bburdette** [judah/terminfo#5]
Trying to build purescript on my bananapi ARM computer, got errors.  Using ghc 7.8.2 and llvm 3.4.2 on Arch.  

[bananapi@lemaker ~]$ cabal install purescript
Resolving dependencies...
Downloading ansi-terminal-0.6.2.1...
Downloading file-embed-0.0.7.1...
Configuring text-1.2.0.4...
Downloading pattern-arrows-0.0.2...
Configuring file-embed-0.0.7.1...
Downloading terminfo-0.4.0.0...
Downloading transformers-compat-0.3.3.4...
Downloading utf8-string-1...
Building text-1.2.0.4...
Building file-embed-0.0.7.1...
Installed file-embed-0.0.7.1
Configuring pattern-arrows-0.0.2...
Building pattern-arrows-0.0.2...
Configuring ansi-terminal-0.6.2.1...
Installed pattern-arrows-0.0.2
Building ansi-terminal-0.6.2.1...
Configuring terminfo-0.4.0.0...
Installed ansi-terminal-0.6.2.1
Downloading ansi-wl-pprint-0.6.7.1...
Building terminfo-0.4.0.0...
Configuring transformers-compat-0.3.3.4...
Failed to install terminfo-0.4.0.0
Build log ( /home/bananapi/.cabal/logs/terminfo-0.4.0.0.log ):
Configuring terminfo-0.4.0.0...
configure: WARNING: unrecognized options: --with-compiler, --with-gcc
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking ncurses.h usability... yes
checking ncurses.h presence... yes
checking for ncurses.h... yes
checking for setupterm in -ltinfo... no
checking for setupterm in -lncursesw... yes
configure: creating ./config.status
config.status: creating terminfo.buildinfo
configure: WARNING: unrecognized options: --with-compiler, --with-gcc
Building terminfo-0.4.0.0...
Preprocessing library terminfo-0.4.0.0...
[1 of 7] Compiling System.Console.Terminfo.Base ( System/Console/Terminfo/Base.hs, dist/build/System/Console/Terminfo/Base.o )

/tmp/ghc797_0/ghc797_10.c:4:17:
     fatal error: ffi.h: No such file or directory
     #include "ffi.h"
                     ^
compilation terminated.
Building transformers-compat-0.3.3.4...
Configuring utf8-string-1...
Installed transformers-compat-0.3.3.4
Building utf8-string-1...
Installed utf8-string-1
Configuring ansi-wl-pprint-0.6.7.1...
Building ansi-wl-pprint-0.6.7.1...
Installed ansi-wl-pprint-0.6.7.1
Downloading optparse-applicative-0.11.0.1...
Configuring optparse-applicative-0.11.0.1...
Building optparse-applicative-0.11.0.1...
Installed optparse-applicative-0.11.0.1
Installed text-1.2.0.4
Downloading parsec-3.1.8...
Configuring hashable-1.2.3.1...
Configuring parsec-3.1.8...
Building hashable-1.2.3.1...
Building parsec-3.1.8...
Installed hashable-1.2.3.1
Configuring unordered-containers-0.2.5.1...
Building unordered-containers-0.2.5.1...
Installed unordered-containers-0.2.5.1
Downloading monad-unify-0.2.2...
Configuring monad-unify-0.2.2...
Building monad-unify-0.2.2...
Installed parsec-3.1.8
Installed monad-unify-0.2.2
cabal: Error: some packages failed to install:
haskeline-0.7.1.3 depends on terminfo-0.4.0.0 which failed to install.
purescript-0.6.4.1 depends on terminfo-0.4.0.0 which failed to install.
terminfo-0.4.0.0 failed during the building phase. The exception was:
ExitFailure 1

**Comment by judah** [comment]
I'm closing this comment since `ffi.h` is an internal detail of GHC, not used directly in `terminfo`, so this sounds like it was a more fundamental problem with the GHC install.
