### ISSUE TITLE
build of termino failing with ncurses-6.0

### ISSUE THREAD

**Issue by mimi1vx** [judah/terminfo#7]
Build of ghc-7.10.2 on openSUSE:Factory with ncurses-6.0

+ bonus in ncurses 6 isn't exported cur_term function

    [  324s] "rm" -f libraries/Cabal/Cabal/dist-boot/build/libHSCabal-1.22.4.0.a.contents  
    [  324s] "/usr/bin/ghc" -o utils/ghc-pkg/dist/build/tmp/ghc-pkg -hisuf hi -osuf  o -hcsuf hc -static  -H32m -O  -package-db libraries/bootstrapping.conf  -hide-all-packages -i -iutils/ghc-pkg/. -iutils/ghc-pkg/dist/build -iutils/ghc-pkg/dist/build/autogen -Iutils/ghc-pkg/dist/build -Iutils/ghc-pkg/dist/build/autogen     -optP-include -optPutils/ghc-pkg/dist/build/autogen/cabal_macros.h -package Cabal-1.22.4.0 -package base-4.7.0.1 -package bin-package-db-0.0.0.0 -package binary-0.7.5.0 -package bytestring-0.10.4.0 -package containers-0.5.5.1 -package directory-1.2.1.0 -package filepath-1.3.0.2 -package process-1.2.0.0 -package terminfo-0.4.0.1 -package unix-2.7.0.1 -XHaskell2010  -no-user-package-db -rtsopts      -odir utils/ghc-pkg/dist/build -hidir utils/ghc-pkg/dist/build -stubdir utils/ghc-pkg/dist/build   -optl-L'/home/abuild/rpmbuild/BUILD/ghc-7.10.2/libraries/terminfo/dist-boot/build' -optl-L'/home/abuild/rpmbuild/BUILD/ghc-7.10.2/libraries/bin-package-db/dist-boot/build' -optl-L'/home/abuild/rpmbuild/BUILD/ghc-7.10.2/libraries/Cabal/Cabal/dist-boot/build' -optl-L'/usr/lib/ghc-7.8.3/process-1.2.0.0' -optl-L'/usr/lib/ghc-7.8.3/pretty-1.1.1.1' -optl-L'/usr/lib/ghc-7.8.3/directory-1.2.1.0' -optl-L'/usr/lib/ghc-7.8.3/unix-2.7.0.1' -optl-L'/usr/lib/ghc-7.8.3/time-1.4.2' -optl-L'/usr/lib/ghc-7.8.3/old-locale-1.0.0.6' -optl-L'/usr/lib/ghc-7.8.3/filepath-1.3.0.2' -optl-L'/home/abuild/rpmbuild/BUILD/ghc-7.10.2/libraries/binary/dist-boot/build' -optl-L'/usr/lib/ghc-7.8.3/containers-0.5.5.1' -optl-L'/usr/lib/ghc-7.8.3/bytestring-0.10.4.0' -optl-L'/usr/lib/ghc-7.8.3/deepseq-1.3.0.2' -optl-L'/usr/lib/ghc-7.8.3/array-0.5.0.0' -optl-L'/usr/lib/ghc-7.8.3/base-4.7.0.1' -optl-L'/usr/lib/ghc-7.8.3/integer-gmp-0.5.1.0' -optl-L'/usr/lib/ghc-7.8.3/ghc-prim-0.3.1.0' -optl-L'/usr/lib/ghc-7.8.3/rts-1.0' -optl-ltinfo -optl-lrt -optl-lutil -optl-ldl -optl-lgmp -optl-lm -optl-lrt -optl-ldl -static  -H32m -O  -package-db libraries/bootstrapping.conf  -hide-all-packages -i -iutils/ghc-pkg/. -iutils/ghc-pkg/dist/build -iutils/ghc-pkg/dist/build/autogen -Iutils/ghc-pkg/dist/build -Iutils/ghc-pkg/dist/build/autogen     -optP-include -optPutils/ghc-pkg/dist/build/autogen/cabal_macros.h -package Cabal-1.22.4.0 -package base-4.7.0.1 -package bin-package-db-0.0.0.0 -package binary-0.7.5.0 -package bytestring-0.10.4.0 -package containers-0.5.5.1 -package directory-1.2.1.0 -package filepath-1.3.0.2 -package process-1.2.0.0 -package terminfo-0.4.0.1 -package unix-2.7.0.1 -XHaskell2010  -no-user-package-db -rtsopts      utils/ghc-pkg/dist/build/Main.o utils/ghc-pkg/dist/build/Version.o    
    [  325s] /home/abuild/rpmbuild/BUILD/ghc-7.10.2/libraries/terminfo/dist-boot/build/libHSterminfo-0.4.0.1.a(Base.o): In function `c86A_info':
    [  325s] /tmp/ghc28860_0/ghc28860_6.o:(.text+0x1afa): undefined reference to `cur_term'
    [  325s] /home/abuild/rpmbuild/BUILD/ghc-7.10.2/libraries/terminfo/dist-boot/build/libHSterminfo-0.4.0.1.a(Base.o): In function `c86T_info':
    [  325s] /tmp/ghc28860_0/ghc28860_6.o:(.text+0x1c4d): undefined reference to `cur_term'
    [  325s] /home/abuild/rpmbuild/BUILD/ghc-7.10.2/libraries/terminfo/dist-boot/build/libHSterminfo-0.4.0.1.a(Base.o): In function `s7Df_info':
    [  325s] /tmp/ghc28860_0/ghc28860_6.o:(.text+0x1e48): undefined reference to `cur_term'
    [  325s] /home/abuild/rpmbuild/BUILD/ghc-7.10.2/libraries/terminfo/dist-boot/build/libHSterminfo-0.4.0.1.a(Base.o): In function `s7Ds_info':
    [  325s] /tmp/ghc28860_0/ghc28860_6.o:(.text+0x1e78): undefined reference to `cur_term'
    [  325s] /home/abuild/rpmbuild/BUILD/ghc-7.10.2/libraries/terminfo/dist-boot/build/libHSterminfo-0.4.0.1.a(Base.o): In function `s7Dx_info':
    [  325s] /tmp/ghc28860_0/ghc28860_6.o:(.text+0x1eea): undefined reference to `cur_term'
    [  325s] /home/abuild/rpmbuild/BUILD/ghc-7.10.2/libraries/terminfo/dist-boot/build/libHSterminfo-0.4.0.1.a(Base.o):/tmp/ghc28860_0/ghc28860_6.o:(.text+0x1f48): more undefined references to `cur_term' follow
    [  325s] collect2: error: ld returned 1 exit status
    [  325s] utils/ghc-pkg/ghc.mk:46: recipe for target 'utils/ghc-pkg/dist/build/tmp/ghc-pkg' failed
    [  325s] make[1]: *** [utils/ghc-pkg/dist/build/tmp/ghc-pkg] Error 1
    [  325s] make[1]: *** Waiting for unfinished jobs....
    [  329s] <<ghc: 33118250488 bytes, 2968 GCs, 122718437/408563712 avg/max bytes residency (26 samples), 899M in use, 0.00 INIT (0.00 elapsed), 29.68 MUT (30.23 elapsed), 21.30 GC (21.67 elapsed) :ghc>>
    [  329s] Makefile:71: recipe for target 'all' failed
    [  329s] make: *** [all] Error 2
    [  329s] error: Bad exit status from /var/tmp/rpm-tmp.rOXMkY (%build)
    [  329s]

**Comment by mimi1vx** [comment]
$ readelf -a libncurses.so.6 | grep cur_term
000000228328  006d00000007 R_X86_64_JUMP_SLO 0000000000000000 _nc_cur_term + 0
     109: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND _nc_cur_term@NCURSES6_TINFO_5.7.20081102 (24)
$ readelf -a libncurses.so.5 | grep cur_term
000000225f70  003900000006 R_X86_64_GLOB_DAT 0000000000000000 cur_term + 0
      57: 0000000000000000     0 OBJECT  GLOBAL DEFAULT  UND cur_term@NCURSES_TINFO_5.0.19991023 (29)

maybe is ncurses bug , I'am not found anything newer info about cur_term in ncurses changelog

**Comment by judah** [comment]
Any chance cur_term is only present in libtinfo and not lib(n)curses (or vice versa)?  The Haskell terminfo package has a configure script that's supposed to take care of this, but maybe it's not working properly.  (It checks for setupterm but not cur_term.)
See also the following bug from a few years back:
https://ghc.haskell.org/trac/ghc/ticket/7281

**Comment by mimi1vx** [comment]
from author of ncurses : 

On Sun, Sep 20, 2015 at 06:13:03PM +0200, Ondřej Súkup wrote:
> hello,
>
> why is in ncurses-6.0:
>
> $ readelf -a libncurses.so.6 | grep cur_term
> 000000228328  006d00000007 R_X86_64_JUMP_SLO 0000000000000000 _nc_cur_term + 0
>    109: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND
> _nc_cur_term@NCURSES6_TINFO_5.7.20081102 (24)
>
> $ readelf -a libncurses.so.5 | grep cur_term
>  000000225f70  003900000006 R_X86_64_GLOB_DAT 0000000000000000 cur_term + 0
>     57: 0000000000000000     0 OBJECT  GLOBAL DEFAULT  UND
> cur_term@NCURSES_TINFO_5.0.19991023 (29)

Compare with the source code:

> fgrep -n cur_term *.map
ncurses.map:879:                cur_term;
ncursest.map:344:               _nc_cur_term;
ncursest.map:446:               _nc_get_cur_term;
ncursest.map:447:               _nc_get_cur_term_sp;
ncursestw.map:344:              _nc_cur_term;
ncursestw.map:452:              _nc_get_cur_term;
ncursestw.map:453:              _nc_get_cur_term_sp;
ncursesw.map:186:               cur_term;

For instance, you may be using ncurses 6.0 on OpenSUSE, where they've
bent the rules a little to make tinfo the same as for the threaded
(libncursest) library.  There are as usual pros/cons about doing that.

(I didn't make it easy to do this, but I didn't make it impossible...)

--
Thomas E. Dickey <dickey@invisible-island.net>
http://invisible-island.net
ftp://invisible-island.net

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.10 (GNU/Linux)

iEYEARECAAYFAlX/Dp0ACgkQcCNT4PfkjtsYHQCffPYWY4jyHrnQoVM9Dkr8lSrM
/ZUAoJU3GjLNlNjvtgL8b/VK48sw1gq4
=Q2/b
-----END PGP SIGNATURE-----

**Comment by mimi1vx** [comment]
I tried pass to terminfo configure  script:

libraries/terminfo_CONFIGURE_OPTS = --configure-option= .. LDFLAGS + with-curses-includes=  .. 
but configure all custom flags silently throw away

our workaround for curses6 is  change 'cur_term' in System/Console/Terminfo/Base.hs to _nc_cur_term

**Comment by mimi1vx** [comment]
@judah with workaround it compiles,but : 

    GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
    [1]    12553 segmentation fault (core dumped)  ghci

**Comment by mimi1vx** [comment]
proposed solution by Scott Bahling https://build.opensuse.org/package/view_file/home:sbahling:branches:devel:languages:haskell/ghc/remove-cur_term-usage.patch?expand=1

**Comment by develop7** [comment]
@judah any chance to review mentioned patch and maybe merge it upstream or suggest fixes?

**Comment by develop7** [comment]
@judah here's direct link to patch mentioned above: https://bugzilla.opensuse.org/attachment.cgi?id=650046&action=diff

**Comment by mimi1vx** [comment]
@develop7 is same as in https://github.com/judah/terminfo/pull/8

**Comment by develop7** [comment]
@mimi1vx oh thanks. It is still unreviewed though. @judah what Linux distro are you using for development so I could write a step-by-step bug reproducing guide for you? Assuming reproducing this issue is main problem with it, is it?

**Comment by mimi1vx** [comment]
@develop7 step for reproduce this problem are very simple ... use ncurses build with threads, without fallback to singlethread variant as opensuse:]

**Comment by judah** [comment]
Apologies for the delay in reply.  I took some time to look this over, since in theory the behavior could be platform-specific; but the linked analysis was convincing enough to me that it should be fine.

I've pushed a patch which is a slight adaptation of #8.  Please confirm whether it fixes the openSUSE build for you:
https://github.com/judah/terminfo/commit/96455041834b54f86482741d940a7941c53cd01e

**Comment by mimi1vx** [comment]
@judah Tested in https://build.opensuse.org/project/show/devel:languages:haskell:lts , working without problems.

**Comment by develop7** [comment]
@judah works for me too. Do you think it is worth bumping release so next GHC will have this issue fixed?

**Comment by mimi1vx** [comment]
closing issue, as https://github.com/judah/terminfo/commit/96455041834b54f86482741d940a7941c53cd01e is working for SUSE/openSUSE
@develop7  https://ghc.haskell.org/trac/ghc/ticket/10901#comment:4 , so planned for GHC 8.0.1
